// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// ili9341_pio_cmd //
// --------------- //

#define ili9341_pio_cmd_wrap_target 0
#define ili9341_pio_cmd_wrap 31

static const uint16_t ili9341_pio_cmd_program_instructions[] = {
            //     .wrap_target
    0xe040, //  0: set    y, 0                       
    0xa0ea, //  1: mov    osr, !y                    
    0x6088, //  2: out    pindirs, 8                 
    0x80a0, //  3: pull   block                      
    0xe003, //  4: set    pins, 3                    
    0xa027, //  5: mov    x, osr                     
    0x002a, //  6: jmp    !x, 10                     
    0xe001, //  7: set    pins, 1                    
    0x6008, //  8: out    pins, 8                    
    0xe003, //  9: set    pins, 3                    
    0xe007, // 10: set    pins, 7                    
    0x80a0, // 11: pull   block                      
    0xa027, // 12: mov    x, osr                     
    0x0020, // 13: jmp    !x, 0                      
    0x80a0, // 14: pull   block                      
    0xa047, // 15: mov    y, osr                     
    0x6088, // 16: out    pindirs, 8                 
    0x0052, // 17: jmp    x--, 18                    
    0xe00f, // 18: set    pins, 15                   
    0x007a, // 19: jmp    !y, 26                     
    0x80a0, // 20: pull   block                      
    0xe005, // 21: set    pins, 5                    
    0x6008, // 22: out    pins, 8                    
    0xe007, // 23: set    pins, 7                    
    0x0054, // 24: jmp    x--, 20                    
    0x001f, // 25: jmp    31                         
    0xe306, // 26: set    pins, 6                [3] 
    0x4008, // 27: in     pins, 8                    
    0xe007, // 28: set    pins, 7                    
    0x8020, // 29: push   block                      
    0x005a, // 30: jmp    x--, 26                    
    0xe00f, // 31: set    pins, 15                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ili9341_pio_cmd_program = {
    .instructions = ili9341_pio_cmd_program_instructions,
    .length = 32,
    .origin = -1,
};

static inline pio_sm_config ili9341_pio_cmd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ili9341_pio_cmd_wrap_target, offset + ili9341_pio_cmd_wrap);
    return c;
}
#endif

